version: '3.4'
services:
  chat-db:
    container_name: chat-database
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chat-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3310:3306'

    volumes:
      - my-db:/var/lib/mysql

  chat-ms:
    container_name: chat-server
    platform: linux/x86_64

    build:
      context: ./
      dockerfile: Dockerfile

    links:
      - chat-db
    ports:
      - '8081:8081'

    depends_on:
      - chat-db

volumes:
  my-db: null
