version: '3.4'
services:
  image-db:
    container_name: image-database
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'image-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3311:3306'

    volumes:
      - my-db:/var/lib/mysql

  image-ms:
    container_name: image-server
    platform: linux/x86_64

    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - image-db
    ports:
      - '8082:8082'

    depends_on:
      - image-db

volumes:
  my-db: null
