version: '3.4'
services:
  frontend-ui:
    platform: linux/x86_64
    image: frontend-ui:latest

    links:
      - backend-app:backend

    build:
      network: host
      dockerfile: Dockerfile

    expose:
      - '3000'

  frontend-loadbalancer:
    container_name: frontend-loadbalancer
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-ui
    ports:
      - 4000:4000

volumes:
  my-db: null
