apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canvas-db-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: canvas-db
spec:
  ports:
  - port: 27017
  selector:
    app: canvas-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: canvas-db
  name: canvas-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canvas-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: canvas-db
    spec:
      containers:
      - image: mongo
        name: canvas-db
        args: ["--dbpath","/data/db"]
        volumeMounts:
        - name: canvas-db-persistent-storage
          mountPath: "/data/db"
      volumes:
      - name: canvas-db-persistent-storage
        persistentVolumeClaim:
          claimName: canvas-db-pv-claim