version: '3.4'
services:
  post-db:
    container_name: post-db
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'post-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3312:3306'

    volumes:
      - my-db:/var/lib/mysql

  post-ms:
    container_name: post-server
    platform: linux/x86_64

    build:
      context: ./
      dockerfile: Dockerfile

    links:
      - post-db
    ports:
      - '8083:8083'

    depends_on:
      - post-db

volumes:
  my-db: null
