#include "p18F4520.inc"
    
    CONFIG  OSC = HS
    CONFIG  PWRT = OFF
    CONFIG  WDT = OFF
    CONFIG  PBADEN = OFF
    CONFIG  LVP = OFF
    
WORM_SL	equ	0x050
WORM_FA	equ	0x051
DIR	equ	0x052
        
	org	0x00000
	BRA	MAIN
	
	org	0x00008
	BTFSC	PORTB,RB0
	CALL	INTSW0,FAST
	RETFIE
	
	org	0x00020
MAIN	RCALL	MINIT
LMLOOP	CALL	UPDATE

	RCALL	ED500MS
	BRA	LMLOOP
	BRA	$
	
DRAW	MOVFF	WORM_SL,PORTD
	BSF	PORTA,1	
	CALL	EDMED
	BCF	PORTA,1
	MOVFF	WORM_FA,PORTD
	BSF	PORTA,2
	CALL	EDMED
	BCF	PORTA,2
	RETURN
	
CORR_SL	BTFSS	DIR,0
	CALL	CFOR_SL
	BTFSC	DIR,0
	CALL	CBA_SL
	RETURN
	
CORR_FA	BTFSS	DIR,0
	CALL	CFOR_FA
	BTFSC	DIR,0
	CALL	CBA_FA
	RETURN
	
CFOR_SL	BTFSS	WORM_SL,6
	RETURN
	MOVLW	b'00000001'
	MOVWF	WORM_SL
	RETURN
	
CFOR_FA	BTFSS	WORM_FA,6
	RETURN
	MOVLW	b'00000001'
	MOVWF	WORM_FA
	RETURN
	
CBA_SL	BTFSS	WORM_SL,7
	RETURN
	MOVLW	b'00100000'
	MOVWF	WORM_SL
	RETURN
	
CBA_FA	BTFSS	WORM_FA,7
	RETURN
	MOVLW	b'00100000'
	MOVWF	WORM_FA
	RETURN
	
ROT_SL	BTFSS	DIR,0
	RLNCF	WORM_SL
	BTFSC	DIR,0
	RRNCF	WORM_SL
	RETURN
	
ROT_FA	BTFSS	DIR,0
	RLNCF	WORM_FA
	BTFSC	DIR,0
	RRNCF	WORM_FA
	RETURN
	
UPDATE	CALL	ROT_SL
	CALL	ROT_FA
	CALL	CORR_SL
	CALL	CORR_FA
	CALL	ED500MS
	
	CALL	ROT_FA
	CALL	CORR_FA
	CALL	ED500MS
	RETURN
	
INTSW0	BCF	INTCON,INT0IF	;Reset interupt-flag
	BTG	DIR,0
	RETURN	FAST
	
MINIT	CLRF	WORM_SL
	CLRF	WORM_FA
	INCF	WORM_SL
	INCF	WORM_FA
	MOVLW	b'11111001'
	MOVWF	TRISA
	BSF	TRISB,0
	CLRF	TRISD
	
	MOVLW	b'10010000'	;Enable interupts for global, sw0
	MOVWF	INTCON
	RETURN

;*** DELAY Package ********** 1.0 ************** AND *
IDSHORT equ     0x07D           ; Delay short counter
IDLONG  equ     0x07E           ; Delay long counter
IDVERYL equ     0x07F           ; Delay very long counter

ED300US MOVLW   0x00
        MOVWF   IDSHORT
LNSLOOP DECFSZ  IDSHORT
        GOTO    LNSLOOP
        RETURN

ED10MS  CLRF    IDSHORT         ; Reset delay counters.
        MOVLW   0x20
        MOVWF   IDLONG
LSLOOP  DECFSZ  IDSHORT         ; Count down...
        GOTO    LSLOOP          ; ...until zero!
        DECFSZ	IDLONG          ; Count down again...
        GOTO	LSLOOP          ; ...until zero!
        RETURN	

ED500MS MOVLW	0x10            ; Reset delay counters.
        MOVWF	IDVERYL
LDLOOP  CALL	ED10MS          ; Wait
        CALL	DRAW
	DECFSZ  IDVERYL         ; Count down...
        GOTO    LDLOOP          ; ...until zero!
        RETURN

EDSMALL	MOVLW	0xFF
	MOVWF	0x0F0
LDLOOP0	DECFSZ	0x0F0
	BRA	LDLOOP0
	RETURN
	
EDMED	MOVLW	0x10
	MOVWF	0x0F1
LDLOOP1 CALL	EDSMALL
	DECFSZ	0x0F1
	BRA	LDLOOP1
	RETURN
;*** End of DELAY Package *********************************
	
	end