#include "p18F4520.inc"
    
    CONFIG  OSC = HS
    CONFIG  PWRT = OFF
    CONFIG  WDT = OFF
    CONFIG  PBADEN = OFF
    CONFIG  LVP = OFF
        
SEG0	equ	0x000
SEG1	equ	0x001
SEG2	equ	0x002
SEG3	equ	0x003
SEG4	equ	0x004
SEG5	equ	0x005
SEG6	equ	0x006
SEG7	equ	0x007
DIR	equ	0x008
	org	0x00000
	BRA	MAIN
	
	org	0x00020
MAIN	RCALL	MINIT
LMLOOP	MOVF	DIR
	
	BTFSS	STATUS,Z
	RCALL	ROTATEL
	RCALL	DISPLAY
	
	BTFSC	STATUS,Z
	RCALL	ROTATER
	RCALL	DISPLAY
	
	
	BRA	LMLOOP
	BRA	$
	
ROTATEL	;Start at 0x006 with pointer
	;and advance copying (i) to (i - 1)
	;Finish off with MOVFF last with first
	RETURN
	
ROTATER	;Start at 0x001 with pointer
	;and advance copying (i) to (i + 1)
	;Finish off with MOVFF first and last
	RETURN
	
DISPLAY	;Start at 0x000 with pointer
	;and advance displaying every
	;segment, with delay inbetween
	BSF	PORTC,RC0
	MOVFF	SEG7,PORTD
	RCALL	EDSHORT
	BCF	PORTC,RC0
	
	BSF	PORTE,RE2
	MOVFF	SEG6,PORTD
	RCALL	EDSHORT
	BCF	PORTE,RE2
	
	BSF	PORTE,RE1
	MOVFF	SEG5,PORTD
	RCALL	EDSHORT
	BCF	PORTE,RE1
	
	BSF	PORTE,RE0
	MOVFF	SEG4,PORTD
	RCALL	EDSHORT
	BCF	PORTE,RE0
	
	BSF	PORTA,RA5
	MOVFF	SEG3,PORTD
	RCALL	EDSHORT
	BCF	PORTA,RA5
	
	BSF	PORTA,RA3
	MOVFF	SEG2,PORTD
	RCALL	EDSHORT
	BCF	PORTA,RA3
	
	BSF	PORTA,RA2
	MOVFF	SEG1,PORTD
	RCALL	EDSHORT
	BCF	PORTA,RA2
	
	BSF	PORTA,RA1
	MOVFF	SEG0,PORTD
	RCALL	EDSHORT
	BCF	PORTA,RA1
	RETURN
	
MINIT	BCF	TRISC,RC0
	CLRF	TRISE
	CLRF	TRISA
	CLRF	TRISD
	CLRF	PORTA
	CLRF	PORTC
	CLRF	PORTD
	CLRF	PORTD
	MOVLW	b'01110110'
	MOVWF	SEG2
	MOVLW	b'01111001'
	MOVWF	SEG1
	MOVLW	b'00011110'
	MOVWF	SEG0
	RETURN

	
EDSHORT	MOVLW	0xFF
	MOVWF	0x0F0
LDLOOP	DECFSZ	0x0F0
	BRA	LDLOOP
	RETURN
	
	end